### ISSUE TITLE
Gateway has no mechanism for emergency reboot on loss of VPN

### ISSUE THREAD

**Issue by scandox** [evercam/evercam-gateway#18]
In rare cases (such as wholesale transfer of VPN Server to new server) Gateway devices may get stuck failing to connect to VPN. A simple reboot would resolve this issue. We need a mechanism whereby if the Gateway has lost VPN for too long that it will reboot itself automatically.

**Comment by scandox** [comment]
Actually it appears VPN connection is picked back up automatically. So closed.

**Comment by marcoherbst** [comment]
My kind of issue.

:)

m

On 20 August 2015 at 10:09, scandox <notifications@github.com> wrote:

> Closed #18 <https://github.com/evercam/evercam-gateway/issues/18>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-gateway/issues/18#event-387471711>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by scandox** [comment]
Yeah! Imaginary is best! Softether keeps doing good shit to me
