### ISSUE TITLE
Use OnVIF for discovery

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-gateway#2]
@liutingdu  is currently our OnVif discovery expert. She may be able to help

**Comment by liutingdu** [comment]
Java code for discovery is [here](https://github.com/evercam/evercam-networkscan-java/blob/master/src/io/evercam/network/onvif/OnvifDiscovery.java)  :)

**Comment by scandox** [comment]
@marcoherbst @liutingdu as I understand we now have OnVif based discovery
