### ISSUE TITLE
Wrap Gateway as a service

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-gateway#4]

**Comment by azr5318** [comment]
Dan,

I did some research into you're concerns and this is what I've found.  

a. Should we create a specific user designed to run the gateway process? Probably we should.
            I'm not quite sure what you mean by this question.

b. Should we move the gateway code (at present ~/evercam-gateway) to a more system-neutral location? The answer is probably yes.  
             If you do decide to move the code the "friendliest" place that I came across of where it should be moved to from what I understand is into /usr/local because of its place in the directory hierarchy (second).

c. If we do a & b, then we also need to chown -R gatewayuser:gatewayuser evercam-gateway/  - i.e. ensure the gateway specific user owns the code.

d. Then I don't know if Debian 8 still uses LSB compliant init scripts or whether they've changed to Upstart (like Ubuntu) or something like that. Could you look into it?
             Yes Debian is compatible with LSB scripts. (https://wiki.debian.org/systemd)

e. If we use an LSB compliant init script then the command to "start" is:
  chdir $APP_PATH/evercam-gateway/apps/gateway
  mix run --no-halt

**Comment by scandox** [comment]
The heart of this has been moved to #8
