### ISSUE TITLE
WebRTC - Support for Firefox (h264)

### ISSUE THREAD

**Issue by rajmohanb** [evercam/evercam-gateway#44]
Currently all the testing has been done on Google Chrome (chromium). Support for Firefox must be added and the same functionality must be viewable on Firefox.

Support Microsoft Edge - probably later

**Comment by rajmohanb** [comment]
Streaming plugin of Janus provides a way to directly take input from RTSP URL and then send the media to the connected WebRTC endpoints. Since the input from camera's is usually H264, and Firefox supports H264 only as of now, this avoids the transcoding of video and frees up the gateway cpu for other important work.

**Comment by marcoherbst** [comment]
We consider this a "Top Priority" as it could allow us to eliminate a lot of the GStreamer related problems.

**Comment by rajmohanb** [comment]
Tested this on Firefox and noticed the following

1. The time between video rendering on the client browser and the captured video remains same even after a long time
2. CPU utilization is quite minimal. Both Janus and Gstreamer each take around 1% on my low end system (Max I noticed was 1.5%).

The Gstreamer pipeline is just a dummy now which takes from the IP camera and passes it to Janus on the local port.

**Comment by marcoherbst** [comment]
Great, that is very good to know. So, that means that the CPU and increasing lag issues can be confidently put down to transcoding. We can now happily leave them to one side and worry about them separately, later. Nice one.

**Comment by rajmohanb** [comment]
**Steps to reproduce**

1. Modify/replace the Janus configuration file as below - https://gist.github.com/rajmohanb/a762a0a84e7eca646784
2. Restart Janus
3. On another terminal, run gstreamer with the following pipeline
    gst-launch-1.0 rtspsrc location=rtsp://admin:12345@192.168.1.100/h264/ch1/main/av_stream name=src ! udpsink host=127.0.0.1 port=8004
4. Goto the webserver on Firefox and connect.

**Comment by rajmohanb** [comment]
![evercam_janus_ffox](https://cloud.githubusercontent.com/assets/3262724/10507635/768428ac-733f-11e5-873d-7b35bc01e116.png)

Notice the terminal on right-bottom corner with CPU usage for both Janus and Gstreamer

**Comment by rajmohanb** [comment]
**Note:** It is possible to use Janus to directly get input packets from RTSP server. There is an example of the same in the sample configuration file. But using gstreamer here to make it symmetrical as when using VP8.

**Comment by rajmohanb** [comment]
This has been verified on Firefox. It can be deduced now that - issue #49 related to the rendered video lag can be attributed to gstreamer transcoding.
