### ISSUE TITLE
Create endpoints to allow the gateway to use WiFi

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-gateway#5]

**Comment by scandox** [comment]
I don't know what this one means. Refresh my memory.

**Comment by marcoherbst** [comment]
@scandox me too. delete.
m

On 8 July 2015 at 01:28, scandox <notifications@github.com> wrote:

> I don't know what this one means. Refresh my memory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-gateway/issues/5#issuecomment-119380905>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst
