### ISSUE TITLE
Enable secure WebSocket for nginx reverse proxy

### ISSUE THREAD

**Issue by rajmohanb** [evercam/evercam-gateway#54]
When the gateway webpage is served over HTTPS (https://gateway.evercam.io/), Chrome declines to connect over plain WS. Hence WSS needs to be enabled for the Nginx reverse proxy (WS relay).

**Comment by liutingdu** [comment]
As discussed, @rajmohanb is going to add the detailed steps to the [setup document](https://docs.google.com/document/d/1_jJNMRy7aXngVRQPjO7VOMrnocwYxENsArxf5Gyn4fU/edit).   
Then I'll follow the steps adding it to our gateway

**Comment by rajmohanb** [comment]
@liutingdu I have updated section 4 of this document accordingly

**Comment by rajmohanb** [comment]
@liutingdu - Self signed certificates are for testing only, they can not be used for production/deployment. So for deployment, we need to use certificates from third party CAs.

**Comment by rajmohanb** [comment]
The nginx works fine on WSS transport as a reverse proxy after copying the third party issued certificates.
