### ISSUE TITLE
Janus not processing signaling HTTP packet

### ISSUE THREAD

**Issue by rajmohanb** [evercam/evercam-gateway#57]
After enabling WSS on nginx, Janus is not processing incoming signaling packets and closes the connection. As soon as it receives a GET request for "/janus", it closes the connection with nginx proxy.

**Comment by rajmohanb** [comment]
Janus is dropping because the HTTP request received has a size more than 1024 bytes. Janus internally makes use of libwebsocket for WSS and this limitation is part of lws library.

2 possible ways to handle this issue

- Recompile libwebsockets to handle higher size messages
- Remove unwanted headers (such as cookie) from the request when proxying bu nginx.

**Comment by rajmohanb** [comment]
Going ahead with option 1. Recompile the libwebsockets library after modifying the LWS_MAX_HEADER_LEN to 2048 bytes from existing/default 1024 bytes.

Updated the [setup document](https://docs.google.com/document/d/1_jJNMRy7aXngVRQPjO7VOMrnocwYxENsArxf5Gyn4fU/edit)  (page 5) accordingly, to modify the LWS_MAX_HEADER_LEN variable.

**Comment by rajmohanb** [comment]
With the above changes, HTTP messages (< 2K) are processed properly and session gets setup.

**Comment by marcoherbst** [comment]
Well done. Good find. Good fix.
